### PR TITLE
add query order by customer id scenario in orders.feature

### PR DESCRIPTION
**Pull request by JoanneWooW**
* add query order by customer id scenario in orders.feature

### CODE REVIEW

**Review by OliverZWang — APPROVED** [review]
LGTM, thank you!

**Review by nbhagat3136 — COMMENTED** [review]
Hi . I was wondering why config.py is checked in for this BDD scenario. Can u check from your end before merging to main branch Is that really necessary. Thanks

**Comment by JoanneWooW** [comment]
@nbhagat3136 Hi, thank you for your reviewing! However, I didn't get your question. Could you please clarify what do you mean by "checked in"? Do you mean why it's been changed?

**Comment by nbhagat3136** [comment]
Right . I can see two files added for this issue. One of them is config.py. So  wanted to confirm with you is that intended file to be added for this change.

**Comment by OliverZWang** [comment]
> Right . I can see two files added for this issue. One of them is config.py. So wanted to confirm with you is config.py intended file to be added for this change.

If you look at the actual changes to the files, she only deleted the "new line" character in `config.py`, which is probably not necessary but also does no harm. So I think it is okay the way it is.

**Comment by nbhagat3136** [comment]
Oh I see thanks for confirming. Looks good to me as well 👍

**Review by nbhagat3136 — APPROVED** [review]

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210810-034216 "deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210810-034216") to [dev](https://console.bluemix.net/apps/ca1654de-b343-467b-953c-97ab2998ca8b?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:dev"), including commit 35a1eb3bb24b99a1d47be42f36d6c061408feef4

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036 "deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036") to [prod](https://console.bluemix.net/apps/f43af9cd-c881-41ff-b5bd-1ee109712701?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:prod"), including commit 35a1eb3bb24b99a1d47be42f36d6c061408feef4

**Pull request merged**
