### PR TITLE
Add BDD Test Case for Cancelling

### PR DESCRIPTION
**Pull request by OliverZWang**

### CODE REVIEW

**Review by pkutlesa — APPROVED** [review]
Looks good :)

**Review by nbhagat3136 — APPROVED** [review]
Look good. Thanks.

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210810-034216 "deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210810-034216") to [dev](https://console.bluemix.net/apps/ca1654de-b343-467b-953c-97ab2998ca8b?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:dev"), including commit 947819e9d4c39cf16266f3e51de842e32e2cea73

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036 "deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036") to [prod](https://console.bluemix.net/apps/f43af9cd-c881-41ff-b5bd-1ee109712701?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:prod"), including commit 947819e9d4c39cf16266f3e51de842e32e2cea73

**Pull request merged**
