### PR TITLE
BDD for List

### PR DESCRIPTION
**Pull request by nbhagat3136**
Implemented BDD for List Orders

### CODE REVIEW

**Review by pkutlesa — CHANGES_REQUESTED** [review]
nitpicks: 
* remove the extra space at the beginning of line 123 
* remove the extra line 78 or 79

**Comment by nbhagat3136** [comment]
Good catch. This has been taken care.

**Review by pkutlesa — CHANGES_REQUESTED** [review]
One more thing: I think order matters in BDD. Please relocate the list scenario to be before the update scenario which relies on the list functionality.

**Comment by nbhagat3136** [comment]
Regarding that I think the order should be following the issue list as per the user story priority. As per our sprint review discussion. So it can  be ahead of cancelling but not next to update.

**Comment by pkutlesa** [comment]
Ok. I agree with preserving the order of user stories

**Review by pkutlesa — APPROVED** [review]
Looks good. Thanks :)

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210810-034216 "deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210810-034216") to [dev](https://console.bluemix.net/apps/ca1654de-b343-467b-953c-97ab2998ca8b?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:dev"), including commit 2d34e5e3b2e16194b783e87dd7e2bc55fd3646b6

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036 "deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036") to [prod](https://console.bluemix.net/apps/f43af9cd-c881-41ff-b5bd-1ee109712701?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:prod"), including commit 2d34e5e3b2e16194b783e87dd7e2bc55fd3646b6

**Pull request merged**
