### PR TITLE
setup bdd 

### PR DESCRIPTION
**Pull request by pkutlesa**
This PR introduces bdd. The following updates were made: 
* behave file structure 
* added bdd dependencies to requirements.txt 
* updated Vagrantfile to install chromium driver  
* test fixtures in environment.py
* sample data and load functionality 
* scenario and steps for testing the running server

### CODE REVIEW

**Review by luke0zong — CHANGES_REQUESTED** [review]
For `Vagrantfile`:

line 38:
`      docker.image = "rofrano/vagrant-provider:ubuntu"`
change to:
```
      # Chromium driver does not work with ubuntu so we use debian
      override.vm.hostname = "debian"
      docker.image = "rofrano/vagrant-provider:debian"
```

line 75:
`apt-get install -y git tree wget vim python3-dev python3-pip python3-venv apt-transport-https`

add `python3-selenium` to the end

**Comment by pkutlesa** [comment]
nice catch!

**Review by luke0zong — APPROVED** [review]
👍

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210728-185907 "deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210728-185907") to [dev](https://console.bluemix.net/apps/e62f7c23-4373-4ba4-9883-ef7ff096b861?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:dev"), including commit 81252e12402273df690f945ffd879b966c001fab

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036 "deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036") to [prod](https://console.bluemix.net/apps/f43af9cd-c881-41ff-b5bd-1ee109712701?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:prod"), including commit 81252e12402273df690f945ffd879b966c001fab

**Pull request merged**
