### PR TITLE
Update manifest.yml

### PR DESCRIPTION
**Pull request by luke0zong**
- Increase instance memory limit to 256MB.

### CODE REVIEW

**Review by nbhagat3136 — APPROVED** [review]
Looks good.

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210725-134304 "deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210725-134304") to [dev](https://console.bluemix.net/apps/e62f7c23-4373-4ba4-9883-ef7ff096b861?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:dev"), including commit 592b91dad81c031c74d8e4a0c58219ed0bb64ef1

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210725-163857 "deploy-ibm-yp-us-south-zw1400-nyu.edu-dev-20210725-163857") to [dev](https://console.bluemix.net/apps/e62f7c23-4373-4ba4-9883-ef7ff096b861?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:dev"), including commit 592b91dad81c031c74d8e4a0c58219ed0bb64ef1

**Comment by pkutlesa** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/9bf05db0-f920-4eb7-a171-e66653f00e58?env_id=ibm:yp:us-south "nyu-order-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/907055a0-7191-42af-9b3d-3504d7e9adb4 "nyu-order-service-sum21") deployed [orders](https://github.com/DevOps-Agile-Squad/orders/releases/tag/deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036 "deploy-ibm-yp-us-south-zw1400-nyu.edu-prod-20210810-061036") to [prod](https://console.bluemix.net/apps/f43af9cd-c881-41ff-b5bd-1ee109712701?env_id=ibm:yp:us-south "ibm:yp:us-south:zw1400@nyu.edu:prod"), including commit 592b91dad81c031c74d8e4a0c58219ed0bb64ef1

**Pull request merged**
